version: '3.5'

services:
#  backend:
#    container_name: _backend_container
#    build:
#      context: .
#    image: -server
#    environment:
#      PORT: 3096
#    ports:
#      - "3096:3096"
#    depends_on:
#      - postgresdb

  postgresdb:
    image: postgres:latest
    container_name: seataxi_postgresdb_container
    ports:
      - "5432:5432"
    env_file: ./.env
    environment:
        POSTGRES_DB: "${DATABASE}"
        POSTGRES_USER: "${DATABASE_USERNAME}"
        POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - postgres-data:/data/db
    restart: always

volumes:
  postgres-data:
    driver: local

networks:
  postgresdb:
    driver: bridge